title: Pedro Cordero-Jara
logo: /assets/img/porftolio-profile.jpg
description: Artificial Intelligence & Robotics | CS Master’s Student | Electronics Engineer
show_downloads: false
theme: jekyll-theme-minimal

# Add personal details
author: Pedro Alejandro Cordero Jara
email: corderopedro593@gmail.com
linkedin: https://www.linkedin.com/in/pedrocorderoj/
github: https://github.com/PedroCordero
location: Budapest, Hungary
